import {
  DERIVED_KEYS,
  billLine,
  buildCreatePayload,
  isBilled,
  itemCountLabel,
  linesTotal,
  newLine,
  orderLines,
  orderTotal,
  passthroughItems,
  toFormState,
  toUpdatePayload,
  type OrderDetailItem,
  type OrderFormState,
} from './orderDetail.model';
import type { OrderLine } from './orderLineUnits';

/** A realistic fetched order: two product lines, one package row, and the derived extras. */
function serverOrder(): OrderDetailItem {
  return {
    id: 42,
    businessId: 3,
    orderNumber: 'ORD-05082026-042',
    customerId: 7,
    customerFirstName: 'Rahul',
    customerLastName: 'Mehta',
    customerPhoneNumber: '+91 98765 43210',
    customerEmail: 'rahul@mail.com',
    orderStatus: 'CONFIRMED',
    notes: 'Deliver before 6 PM.',
    totalAmount: 626,
    orderDate: '2026-08-05T08:44:00Z',
    dmsFolderId: 91,
    isBilled: false,
    billId: null,
    subscriptionId: null,
    isAutoGenerated: false,
    createdAt: '2026-08-05T08:44:00Z',
    updatedAt: '2026-08-05T09:10:00Z',
    billNumber: null,
    linkedAppointmentNumbers: {},
    orderedProductItemsWithDetails: [{ productId: 5, productName: 'Paracetamol' }],
    orderItems: [
      {
        type: 'PRODUCT',
        productId: 5,
        salesPersonId: 2,
        quantity: 2,
        itemPrice: 28,
        totalPrice: 56,
        discount: 0,
        sellingUnit: 'strip',
        unitMultiplier: 10,
        status: 'DELIVERED',
        productSnapshot: { name: 'Paracetamol 500mg', brand: 'Cipla' },
        inventoryLine: { deducted: 20 },
        returnReason: null,
      },
      {
        // No `type` at all — Jackson's defaultImpl is OrderedProductItem, so this IS a product row.
        productId: 9,
        quantity: 1,
        itemPrice: 120,
        totalPrice: 120,
        discount: 0,
        sellingUnit: 'bottle',
        unitMultiplier: 1,
      },
      {
        type: 'PACKAGE',
        packageId: 3,
        packageName: 'Bridal Package',
        quantity: 1,
        itemPrice: 450,
        totalPrice: 450,
        discount: 0,
        fulfillments: [
          {
            fulfillmentId: 'uuid-1',
            status: 'PENDING',
            linkedTransactionId: 88,
            origin: 'PACKAGE',
          },
        ],
      },
    ],
  };
}

describe('orderLines / passthroughItems', () => {
  it('treats an untyped row as a product, because Jackson defaultImpl says it is one', () => {
    // Reading only `type === 'PRODUCT'` would silently drop every line the web portal wrote
    // without a discriminator — and a dropped line is a restocked line.
    expect(orderLines(serverOrder()).map((l) => l.productId)).toEqual([5, 9]);
  });

  it('keeps the non-product rows separate rather than dropping them', () => {
    const extra = passthroughItems(serverOrder());
    expect(extra).toHaveLength(1);
    expect(extra[0].type).toBe('PACKAGE');
  });

  it('handles an order with no items', () => {
    expect(orderLines({ id: 1 })).toEqual([]);
    expect(passthroughItems(null)).toEqual([]);
  });
});

describe('toFormState', () => {
  it('reads the four editable things and the lines', () => {
    const form = toFormState(serverOrder());
    expect(form.orderStatus).toBe('CONFIRMED');
    expect(form.notes).toBe('Deliver before 6 PM.');
    expect(form.customerId).toBe(7);
    expect(form.customerName).toBe('Rahul Mehta');
    expect(form.customerPhone).toBe('+91 98765 43210');
    expect(form.lines).toHaveLength(2);
  });

  it('defaults a new order to CONFIRMED, matching the server mapper', () => {
    expect(toFormState(null).orderStatus).toBe('CONFIRMED');
    expect(toFormState({}).notes).toBe('');
    expect(toFormState({}).customerId).toBeNull();
  });
});

describe('toUpdatePayload — the erasure hazard', () => {
  const form = (over: Partial<OrderFormState> = {}): OrderFormState => ({
    ...toFormState(serverOrder()),
    ...over,
  });

  it('sends every NOT NULL field, because omitting one is an HTTP 500 not a 4xx', () => {
    // customerId / businessId / totalAmount are copied unguarded onto a NOT NULL column. Postgres
    // raises 23502 and Modulex maps that to 500.
    const p = toUpdatePayload(serverOrder(), form(), passthroughItems(serverOrder()));
    expect(p.customerId).toBe(7);
    expect(p.businessId).toBe(3);
    expect(typeof p.totalAmount).toBe('number');
  });

  it('sends orderStatus, so a save cannot silently reset the order to CONFIRMED', () => {
    // Unlike the NOT NULL fields this one fails quietly: the mapper defaults a null to CONFIRMED,
    // so a REJECTED order would come back confirmed with no error anywhere.
    const p = toUpdatePayload(serverOrder(), form({ orderStatus: 'REJECTED' }), []);
    expect(p.orderStatus).toBe('REJECTED');
  });

  it('sends orderItems in full even when nothing was edited', () => {
    const item = serverOrder();
    const p = toUpdatePayload(item, form(), passthroughItems(item));
    expect((p.orderItems as unknown[]).length).toBe(3);
  });

  it('keeps the PACKAGE row, which the form cannot edit and must not delete', () => {
    // Dropping it orphan-removes the row AND restocks units already handed to a customer.
    const item = serverOrder();
    const p = toUpdatePayload(item, form(), passthroughItems(item));
    const pkg = (p.orderItems as Record<string, unknown>[]).find((r) => r.type === 'PACKAGE');
    expect(pkg).toBeDefined();
    expect((pkg as Record<string, unknown>).fulfillments).toEqual([
      { fulfillmentId: 'uuid-1', status: 'PENDING', linkedTransactionId: 88, origin: 'PACKAGE' },
    ]);
  });

  it('keeps productSnapshot and the other no-UI fields on every product line', () => {
    // productSnapshot is the frozen display copy that survives a catalog delete; dropping it breaks
    // the row's rendering after the product is gone.
    const item = serverOrder();
    const p = toUpdatePayload(item, form(), passthroughItems(item));
    const line = (p.orderItems as Record<string, unknown>[])[0];
    expect(line.productSnapshot).toEqual({ name: 'Paracetamol 500mg', brand: 'Cipla' });
    expect(line.status).toBe('DELIVERED');
    expect(line.salesPersonId).toBe(2);
  });

  it('echoes the fields with no mobile UI rather than dropping them', () => {
    const p = toUpdatePayload(serverOrder(), form(), passthroughItems(serverOrder()));
    expect(p.dmsFolderId).toBe(91);
    expect(p.orderNumber).toBe('ORD-05082026-042');
    expect(p.orderDate).toBe('2026-08-05T08:44:00Z');
    expect(p.isAutoGenerated).toBe(false);
  });

  it('strips only the derived keys', () => {
    const p = toUpdatePayload(serverOrder(), form(), passthroughItems(serverOrder()));
    for (const key of DERIVED_KEYS) expect(p).not.toHaveProperty(key);
  });

  it('puts the id in the BODY — the endpoint has no path variable', () => {
    expect(toUpdatePayload(serverOrder(), form(), []).id).toBe(42);
  });

  it('sends notes as a string always, so a cleared note actually clears', () => {
    // The server null-guards notes: null means "leave it alone". Omitting the key would make
    // clearing impossible — the exact bug the web portal's appointment form has.
    const p = toUpdatePayload(serverOrder(), form({ notes: '' }), []);
    expect(p.notes).toBe('');
  });

  it('trims the note rather than storing the whitespace someone left behind', () => {
    expect(toUpdatePayload(serverOrder(), form({ notes: '  hi  ' }), []).notes).toBe('hi');
  });

  it('recomputes totalAmount from the lines INCLUDING the passthrough rows', () => {
    // 56 + 120 products + 450 package. Counting only the editable lines would shrink the order on
    // every save from a phone.
    const item = serverOrder();
    const p = toUpdatePayload(item, form(), passthroughItems(item));
    expect(p.totalAmount).toBe(626);
  });
});

describe('buildCreatePayload', () => {
  const form: OrderFormState = {
    orderStatus: 'CONFIRMED',
    notes: 'call on arrival',
    customerId: 7,
    customerName: 'Rahul Mehta',
    customerPhone: '900',
    customerEmail: '',
    lines: [{ productId: 5, quantity: 2, itemPrice: 28, totalPrice: 56, discount: 0 } as OrderLine],
  };

  it('carries the required fields and no id', () => {
    const p = buildCreatePayload(form, 3);
    expect(p.businessId).toBe(3);
    expect(p.customerId).toBe(7);
    expect(p.orderStatus).toBe('CONFIRMED');
    expect(p.totalAmount).toBe(56);
    expect(p).not.toHaveProperty('id');
  });

  it('does NOT send orderDate — the server stamps it and ignores anything sent', () => {
    // OrderMapper.toEntity never copies it, so sending one would imply a control the app lacks.
    // Which is also why the Add and Edit mockups have no Order Date picker.
    expect(buildCreatePayload(form, 3)).not.toHaveProperty('orderDate');
  });
});

describe('totals', () => {
  const mixed: OrderLine = {
    productId: 5,
    quantity: 14,
    itemPrice: 52 / 14,
    totalPrice: 52,
    discount: 0,
    unitLines: [
      { unit: 'strip', perStock: 10, qty: 1, price: 28 },
      { unit: 'tablet', perStock: 1, qty: 4, price: 6 },
    ],
  };

  it('totals a mixed line per unit rather than from its blended price', () => {
    expect(linesTotal([mixed])).toBe(52);
  });

  it('adds the passthrough rows in', () => {
    expect(orderTotal([mixed], [{ totalPrice: 450 }])).toBe(502);
    expect(orderTotal([mixed], [{}])).toBe(52);
  });
});

describe('newLine', () => {
  it('seeds a picked product at quantity 1 on the given rung', () => {
    const line = newLine(5, { unit: 'strip', perStock: 10, price: 28 }, 2);
    expect(line).toMatchObject({
      productId: 5,
      salesPersonId: 2,
      quantity: 1,
      itemPrice: 28,
      totalPrice: 28,
      sellingUnit: 'strip',
      unitMultiplier: 10,
      status: 'PENDING',
    });
  });

  it('copes with a product that has no sale units', () => {
    const line = newLine(5, null, null);
    expect(line.sellingUnit).toBeUndefined();
    expect(line.unitLines).toBeNull();
    expect(line.itemPrice).toBe(0);
  });
});

describe('read-mode helpers', () => {
  it('pluralises the item count and counts the passthrough rows', () => {
    expect(itemCountLabel([{} as OrderLine])).toBe('1 item');
    expect(itemCountLabel([{} as OrderLine, {} as OrderLine], [{}])).toBe('3 items');
    expect(itemCountLabel([])).toBe('0 items');
  });

  it('says whether the order is on a bill, preferring the number', () => {
    expect(billLine(serverOrder())).toBe('Not on a bill yet');
    expect(billLine({ billNumber: 'BILL-05082026-014' })).toBe('On bill BILL-05082026-014');
    expect(billLine({ billId: 52 })).toBe('On a bill');
    expect(billLine(null)).toBe('Not on a bill yet');
  });

  it('reports the billed lock', () => {
    expect(isBilled(serverOrder())).toBe(false);
    expect(isBilled({ isBilled: true })).toBe(true);
    expect(isBilled(null)).toBe(false);
  });
});
