/**
 * Form mapping and the payload builders for the Order Detail screen.
 *
 * RN-free on purpose, so the repo's plain-node jest covers it — `jest.config.js` matches
 * `*.test.ts` only, and anything that ends up in a `.tsx` is untestable here by construction.
 *
 * The single most important thing in this file is `toUpdatePayload`. `PUT /{module}Order` is a
 * FULL-OBJECT replace: `GenericOrderService.updateOrder` copies every field off the request onto
 * the record, so a field missing from the request is not "left alone", it is erased. The builder
 * therefore starts from the DTO the server last gave us and overlays the edits.
 *
 * `orderItems` is the field that makes this dangerous rather than merely wrong. The update does
 * `existing.setOrderItems(validated)` with `incoming = newData.getOrderItems() != null ? … :
 * List.of()`, then `reverseRemoved` **restocks every deducted unit** for any product that vanished
 * from the list. Modulex's own comment at `GenericOrderService.java:2029-2037` calls this out as
 * "the exact package-drop class of bug".
 */

import { displayUnitLines, lineTotal, type OrderLine, type UnitLine } from './orderLineUnits';

// Re-exported so the detail screen has one import surface, and so a card and a record can never
// disagree about how money, a date or a status reads.
export {
  formatAmount,
  formatOrderDate,
  formatOrderStamp,
  initialsOf,
  itemStatusLabel,
  statusLabel,
  STATUS_ORDER,
} from '../order.model';

// ─── Types ───────────────────────────────────────────────────────────────────

/** Loose server order. The DTO carries far more than the form touches, and that is the point. */
export interface OrderDetailItem {
  id?: number | null;
  businessId?: number | null;
  [k: string]: unknown;
}

export interface OrderFormState {
  /** The only three things the form may write, plus the lines. Everything else round-trips. */
  orderStatus: string;
  notes: string;
  customerId: number | null;
  customerName: string;
  customerPhone: string;
  customerEmail: string;
  lines: OrderLine[];
}

/**
 * Server-derived keys stripped before a write.
 *
 * Short, and deliberately so. `orderNumber`, `orderDate`, `isBilled`, `billId`, `subscriptionId`
 * and `isAutoGenerated` are NOT here even though the form never edits them: the update path never
 * copies them onto the record, so echoing them is harmless, and *removing* them would be a
 * behaviour change with no upside. Only the four the server recomputes or refuses are dropped.
 *
 * `orderedProductItemsWithDetails` is the enriched, read-only mirror of `orderItems`. Modulex marks
 * it `@JsonProperty(access = READ_ONLY)` and has a regression test proving an echo deserialises
 * cleanly, so either way is safe — it is dropped because sending a second copy of every line, each
 * carrying a nested product, is a lot of bytes to no purpose.
 */
export const DERIVED_KEYS = [
  'createdAt',
  'updatedAt',
  'billNumber',
  'linkedAppointmentNumbers',
  'orderedProductItemsWithDetails',
] as const;

// ─── Primitives ──────────────────────────────────────────────────────────────

function str(v: unknown): string {
  if (v === null || v === undefined) return '';
  return String(v);
}

export function toNumberOrNull(v: unknown): number | null {
  if (v === null || v === undefined) return null;
  const s = String(v).trim();
  if (s === '') return null;
  const n = Number(s);
  return Number.isFinite(n) ? n : null;
}

// ─── Lines ───────────────────────────────────────────────────────────────────

/**
 * The order's lines, as editable rows.
 *
 * Only PRODUCT rows. A saved order can also hold PACKAGE, SERVICE_PLAN and SUBSCRIPTION rows, and
 * those are **read-only on mobile** — there is no UI to build one, and the picker only offers
 * products. They are not dropped, though: see `passthroughItems`.
 */
export function orderLines(item: OrderDetailItem | null): OrderLine[] {
  const raw = Array.isArray(item?.orderItems)
    ? (item?.orderItems as Record<string, unknown>[])
    : [];
  return raw.filter(isProductItem) as unknown as OrderLine[];
}

/**
 * The rows the form does NOT edit, kept so they can be written straight back.
 *
 * This is the difference between an edit and a silent deletion. A package row dropped from the
 * payload is orphan-removed by `setOrderItems`, and `reverseRemoved` then restocks units that were
 * already handed to a customer. The mobile screen cannot build one of these rows, so its only job
 * is to not lose them.
 */
export function passthroughItems(item: OrderDetailItem | null): Record<string, unknown>[] {
  const raw = Array.isArray(item?.orderItems)
    ? (item?.orderItems as Record<string, unknown>[])
    : [];
  return raw.filter((row) => !isProductItem(row));
}

function isProductItem(row: Record<string, unknown> | null | undefined): boolean {
  if (!row) return false;
  const type = str(row.type).toUpperCase();
  // `defaultImpl` is OrderedProductItem, so an untyped row IS a product row — the server's own
  // Jackson config says so. Reading only `type === 'PRODUCT'` would silently drop every line the
  // web portal wrote without one.
  return type === '' || type === 'PRODUCT';
}

/** Sum of the lines. Display only — the server recomputes nothing, but it validates `totalAmount`. */
export function linesTotal(lines: OrderLine[]): number {
  return lines.reduce((sum, line) => sum + lineTotal(line), 0);
}

/**
 * The whole order's total, INCLUDING the rows the form cannot edit.
 *
 * A package row still costs money. Sending a `totalAmount` that counts only the product lines
 * would quietly shrink the order every time it is saved from a phone.
 */
export function orderTotal(lines: OrderLine[], passthrough: Record<string, unknown>[]): number {
  const extra = passthrough.reduce((sum, row) => sum + Number(row?.totalPrice ?? 0), 0);
  return linesTotal(lines) + extra;
}

/** A new line for a product the user just picked, seeded on its base rung. */
export function newLine(
  productId: number,
  unit: { unit: string; perStock: number; price: number } | null,
  salesPersonId: number | null,
): OrderLine {
  const price = unit?.price ?? 0;
  return {
    productId,
    salesPersonId,
    quantity: 1,
    itemPrice: price,
    totalPrice: price,
    discount: 0,
    status: 'PENDING',
    ...(unit ? { sellingUnit: unit.unit, unitMultiplier: unit.perStock } : {}),
    unitLines: unit ? ([{ ...unit, qty: 1 }] as UnitLine[]) : null,
  };
}

// ─── DTO ⇄ form ──────────────────────────────────────────────────────────────

export function toFormState(item: OrderDetailItem | null): OrderFormState {
  const first = str(item?.customerFirstName).trim();
  const last = str(item?.customerLastName).trim();
  return {
    orderStatus: str(item?.orderStatus) || 'CONFIRMED',
    notes: str(item?.notes),
    customerId: toNumberOrNull(item?.customerId),
    customerName: [first, last].filter(Boolean).join(' ') || str(item?.customerName),
    customerPhone: str(item?.customerPhoneNumber),
    customerEmail: str(item?.customerEmail),
    lines: orderLines(item),
  };
}

/**
 * The fields the form is allowed to write. Everything else on the DTO passes through untouched.
 *
 * `notes` is sent as a string always, never omitted. The server null-guards it — null means "not
 * provided, leave it alone" — so omitting the key would make clearing a note impossible, which is
 * the bug the web portal's appointment form has today.
 */
function editedFields(
  form: OrderFormState,
  passthrough: Record<string, unknown>[],
): Record<string, unknown> {
  return {
    orderStatus: form.orderStatus,
    notes: form.notes.trim(),
    customerId: form.customerId,
    orderItems: [...form.lines, ...passthrough],
    totalAmount: orderTotal(form.lines, passthrough),
  };
}

/**
 * Build the body for `PUT /{module}Order`.
 *
 * Starts from `serverItem` — the DTO as last fetched — and overlays the edits, because the server
 * replaces the whole record. Four fields are easy to lose and each has its own consequence:
 *
 *  - `customerId`, `businessId`, `totalAmount` — NOT NULL columns copied unguarded. Omit one and
 *    Postgres raises 23502, which Modulex's exception handler maps to **HTTP 500**, not a 4xx.
 *  - `orderStatus` — copied unguarded, and `OrderMapper.toEntity` defaults a null to `CONFIRMED`.
 *    Omitting it does not error; it silently resets the order's status.
 *  - `orderItems` — replaced wholesale, and every product missing from the new list is
 *    **restocked**. This is why `passthroughItems` exists.
 *
 * The id goes in the BODY. `PUT /{module}Order` has no path variable.
 */
export function toUpdatePayload(
  serverItem: OrderDetailItem,
  form: OrderFormState,
  passthrough: Record<string, unknown>[],
): Record<string, unknown> {
  const base: Record<string, unknown> = { ...serverItem };
  for (const key of DERIVED_KEYS) delete base[key];

  return {
    ...base,
    ...editedFields(form, passthrough),
    id: serverItem.id,
    businessId: serverItem.businessId,
  };
}

/**
 * Build the body for `POST /{module}Order`. No id and no passthrough rows — a new order has none.
 *
 * `orderDate` is deliberately absent: `OrderMapper.toEntity` never copies it, so `@PrePersist`
 * stamps `now()` whatever the client sends. Sending one would imply a control the app does not
 * have. (This is also why the Add and Edit mockups have no Order Date picker.)
 */
export function buildCreatePayload(
  form: OrderFormState,
  businessId: number,
): Record<string, unknown> {
  return {
    ...editedFields(form, []),
    businessId,
  };
}

// ─── Read-mode helpers ───────────────────────────────────────────────────────

/** "3 items" / "1 item" — the ITEMS section's count chip. */
export function itemCountLabel(lines: OrderLine[], passthrough: unknown[] = []): string {
  const n = lines.length + passthrough.length;
  return `${n} item${n === 1 ? '' : 's'}`;
}

/**
 * The bill strip under the totals: "Not on a bill yet", or the bill's number.
 *
 * `billNumber` is derived server-side and only present when `billId` is, so the two are checked
 * together rather than trusting either alone.
 */
export function billLine(item: OrderDetailItem | null): string {
  const number = str(item?.billNumber).trim();
  if (number) return `On bill ${number}`;
  return item?.billId != null ? 'On a bill' : 'Not on a bill yet';
}

/** Whether this order is frozen by a finalized bill. The server answers 409 if you try anyway. */
export function isBilled(item: OrderDetailItem | null): boolean {
  return item?.isBilled === true;
}

/** Per-line unit rows, for the view screen's meta line. */
export function lineUnits(line: OrderLine): UnitLine[] {
  return displayUnitLines(line);
}

/**
 * Product names and brands for the lines, taken from the response the screen already has.
 *
 * `orderedProductItemsWithDetails` is the enriched, read-only mirror of `orderItems` that the
 * backend builds by joining each line to its product. It is why view mode needs no catalog fetch:
 * a read-only order can render entirely from its own response.
 *
 * Worth preferring over `productSnapshot`, which is null on every order written before snapshots
 * shipped — a real live order shows `productSnapshot: null` and
 * `productName: "Cristiano Rolandoooooo"` side by side. The snapshot still wins where it exists,
 * because it is frozen at order time and survives the product being renamed or deleted.
 */
export function enrichedDisplay(
  item: OrderDetailItem | null,
): Record<number, { name: string; brand: string }> {
  const rows = Array.isArray(item?.orderedProductItemsWithDetails)
    ? (item?.orderedProductItemsWithDetails as Record<string, unknown>[])
    : [];
  const map: Record<number, { name: string; brand: string }> = {};
  for (const row of rows) {
    const id = Number(row?.productId);
    if (!Number.isFinite(id)) continue;
    map[id] = { name: str(row?.productName), brand: str(row?.brand) };
  }
  return map;
}
