import {
  DERIVED_KEYS,
  appointmentTotal,
  billLine,
  buildCreatePayload,
  enrichedDisplay,
  formatLongDate,
  formatWhen,
  isBilled,
  joinDateTime,
  serviceCountLabel,
  splitDateTime,
  statusLabel,
  toFormState,
  toUpdatePayload,
  type AppointmentDetailItem,
  type AppointmentFormState,
} from './appointmentDetail.model';
import {
  canCompleteItem,
  canCompleteItems,
  displayServices,
  newServiceLine,
  passthroughItems,
  serviceMeta,
  setQuantity,
  unitPrice,
  type ServiceLine,
} from './appointmentLines';

function serverAppointment(): AppointmentDetailItem {
  return {
    id: 12,
    businessId: 3,
    appointmentNumber: 'APT-05082026-001',
    customerId: 7,
    customerFirstName: 'Priya',
    customerLastName: 'Nair',
    customerPhoneNumber: '+91 99887 76655',
    customerEmail: 'priya@mail.com',
    appointmentStatus: 'CONFIRMED',
    notes: "Bride's sister — prefers a subtle look.",
    appointmentDateTime: '2026-08-05T10:00:00',
    appointmentDate: '2026-08-05',
    appointmentTime: '10:00',
    totalAmount: 5000,
    // No mobile UI for any of these three, and all three are silently NULLed if not echoed.
    servicePlanId: 4,
    sessionNumber: 2,
    employmentId: 88,
    isBilled: false,
    billId: null,
    billNumber: null,
    isAutoGenerated: false,
    createdAt: '2026-08-05T03:32:00Z',
    updatedAt: '2026-08-05T03:45:00Z',
    completedAt: null,
    appointmentItemsWithDetails: [
      { serviceId: 21, serviceName: 'Gold Facial Treatment', serviceDuration: 75, unitPrice: 2500 },
    ],
    appointedServiceItems: [{ serviceId: 21, quantity: 1 }],
    appointmentItems: [
      {
        type: 'SERVICE',
        id: 'uuid-item-1',
        serviceId: 21,
        servicePersonId: 2,
        quantity: 1,
        itemPrice: 2500,
        totalPrice: 2500,
        discount: 0,
        status: 'PENDING',
        serviceSnapshot: { name: 'Gold Facial Treatment' },
        addedDuringExecution: false,
      },
      {
        type: 'PACKAGE',
        packageId: 9,
        packageName: 'Bridal Package',
        totalPrice: 2500,
        fulfillments: [{ fulfillmentId: 'uuid-f1', status: 'PENDING', linkedTransactionId: 12 }],
      },
    ],
  };
}

describe('date and time — the zone-less wall clock', () => {
  it('prefers the server-split date and time, which are already IST', () => {
    expect(splitDateTime(serverAppointment())).toEqual({ date: '2026-08-05', time: '10:00' });
  });

  it('falls back to splitting appointmentDateTime by string, never by Date', () => {
    // Parsing with `new Date` reads a zone-less string as device-local: right by accident on an
    // IST phone, wrong in the preview and wrong for anyone travelling.
    expect(splitDateTime({ appointmentDateTime: '2026-08-05T14:30:00' })).toEqual({
      date: '2026-08-05',
      time: '14:30',
    });
  });

  it('is empty when there is nothing to split', () => {
    expect(splitDateTime(null)).toEqual({ date: '', time: '' });
    expect(splitDateTime({})).toEqual({ date: '', time: '' });
  });

  it('recombines with seconds and NO zone, which is what the parser demands', () => {
    // ISO_LOCAL_DATE_TIME: a trailing Z or an offset throws DateTimeParseException server-side.
    expect(joinDateTime('2026-08-05', '10:00')).toBe('2026-08-05T10:00:00');
    expect(joinDateTime('2026-08-05', '10:00:30')).toBe('2026-08-05T10:00:30');
    expect(joinDateTime('2026-08-05', '10:00')).not.toContain('Z');
  });

  it('yields empty rather than a half-built string when a half is missing', () => {
    expect(joinDateTime('', '10:00')).toBe('');
    expect(joinDateTime('2026-08-05', '')).toBe('');
  });

  it('formats the title line and the long date from parts', () => {
    expect(formatWhen('2026-08-05', '10:00')).toBe('5 Aug, 10:00 am');
    expect(formatWhen('2026-08-05', '14:30')).toBe('5 Aug, 2:30 pm');
    expect(formatLongDate('2026-08-05')).toBe('5 Aug 2026');
    expect(formatWhen('', '10:00')).toBe('');
    expect(formatLongDate('nonsense')).toBe('');
  });
});

describe('items', () => {
  it('separates the editable service rows from the package ones', () => {
    expect(displayServices(serverAppointment())).toHaveLength(1);
    expect(passthroughItems(serverAppointment())).toHaveLength(1);
  });

  it('treats an untyped row as a service, because defaultImpl says it is one', () => {
    expect(displayServices({ appointmentItems: [{ serviceId: 5 }] })).toHaveLength(1);
  });

  it('carries the server UUID, which the per-item complete endpoint matches on', () => {
    expect(displayServices(serverAppointment())[0].id).toBe('uuid-item-1');
  });

  it('mints no id for a new line — the server owns that', () => {
    expect(newServiceLine(21, 2500, 2).id).toBeUndefined();
    expect(newServiceLine(21, 2500, 2)).toMatchObject({
      serviceId: 21,
      quantity: 1,
      itemPrice: 2500,
      totalPrice: 2500,
      status: 'PENDING',
    });
  });

  it('keeps the total in step with the quantity, and never goes below one', () => {
    const line = newServiceLine(21, 2500, null);
    expect(setQuantity(line, 3).totalPrice).toBe(7500);
    expect(setQuantity(line, 0).quantity).toBe(1);
    expect(setQuantity(line, -5).quantity).toBe(1);
  });

  it('derives the unit price for a portal-written line instead of pricing it at nothing', () => {
    // The portal's appointment payload sends totalPrice per line and no unit price, so itemPrice
    // comes back null. Reading it as 0 made "+" zero the service — and the appointment total with
    // it, because the total is the sum of the lines.
    const fromPortal = {
      id: 'c2bda72f',
      serviceId: 5,
      quantity: 1,
      itemPrice: null,
      totalPrice: 50,
      discount: 0,
    };
    expect(unitPrice(fromPortal)).toBe(50);
    expect(setQuantity(fromPortal, 2)).toMatchObject({ quantity: 2, itemPrice: 50, totalPrice: 100 });
  });

  it('trusts a real itemPrice over the derived one, including a genuinely free service', () => {
    expect(unitPrice({ serviceId: 5, quantity: 2, itemPrice: 40, totalPrice: 999, discount: 0 })).toBe(40);
    expect(unitPrice({ serviceId: 5, quantity: 2, itemPrice: 0, totalPrice: 0, discount: 0 })).toBe(0);
  });

  it('does not divide by a missing quantity', () => {
    expect(unitPrice({ serviceId: 5, quantity: 0, itemPrice: null, totalPrice: 50, discount: 0 })).toBe(0);
  });

  it('gates completion on PENDING and on having an id', () => {
    // A line the form just created has no UUID, so the endpoint has nothing to match.
    expect(canCompleteItem({ ...newServiceLine(21, 1, null), id: 'u1' })).toBe(true);
    expect(canCompleteItem(newServiceLine(21, 1, null))).toBe(false);
    expect(canCompleteItem({ ...newServiceLine(21, 1, null), id: 'u1', status: 'COMPLETED' })).toBe(
      false,
    );
  });

  it('hides completion entirely on a terminal appointment', () => {
    expect(canCompleteItems('CONFIRMED')).toBe(true);
    expect(canCompleteItems('COMPLETED')).toBe(false);
    expect(canCompleteItems('CANCELLED')).toBe(false);
    expect(canCompleteItems('REJECTED')).toBe(false);
  });

  it('formats the meta line, dropping a duration nobody set', () => {
    const line = { ...newServiceLine(21, 1, null), quantity: 2 };
    expect(serviceMeta(line, 75)).toBe('75 min · Qty 2');
    expect(serviceMeta(line, null)).toBe('Qty 2');
    expect(serviceMeta(line, 0)).toBe('Qty 2');
  });
});

describe('toUpdatePayload — the erasure hazards', () => {
  const form = (over: Partial<AppointmentFormState> = {}): AppointmentFormState => ({
    ...toFormState(serverAppointment()),
    ...over,
  });

  it('sends appointmentStatus even when the DTO never had one', () => {
    // The highest-value test here. AppointmentMapper maps a null status to null and the column is
    // NOT NULL — unlike an order, where the mapper defaults to CONFIRMED. Omitting it is a 500.
    const p = toUpdatePayload(serverAppointment(), form(), []);
    expect(p.appointmentStatus).toBe('CONFIRMED');

    const legacy = { ...serverAppointment() };
    delete legacy.appointmentStatus;
    expect(toUpdatePayload(legacy, toFormState(legacy), []).appointmentStatus).toBe('CONFIRMED');
  });

  it('sends appointmentDateTime as a zone-less wall clock', () => {
    const p = toUpdatePayload(serverAppointment(), form(), []);
    expect(p.appointmentDateTime).toBe('2026-08-05T10:00:00');
  });

  it('echoes servicePlanId, sessionNumber and employmentId, which have no mobile UI', () => {
    // All three are copied unguarded by onUpdateModuleFields and silently NULLed when omitted.
    // employmentId is the assigned-staff field the web portal writes.
    const p = toUpdatePayload(serverAppointment(), form(), []);
    expect(p.servicePlanId).toBe(4);
    expect(p.sessionNumber).toBe(2);
    expect(p.employmentId).toBe(88);
  });

  it('sends every NOT NULL field', () => {
    const p = toUpdatePayload(serverAppointment(), form(), passthroughItems(serverAppointment()));
    expect(p.customerId).toBe(7);
    expect(p.businessId).toBe(3);
    expect(p.totalAmount).toBe(5000);
    expect(p.id).toBe(12);
  });

  it('OMITS the item array entirely rather than sending [], which would erase the services', () => {
    // Inverts the order rule: there, omitting is destructive. Here, sending [] is.
    const p = toUpdatePayload(serverAppointment(), form({ lines: [] }), []);
    expect(p).not.toHaveProperty('appointmentItems');
  });

  it('sends the items when there are some, package rows included', () => {
    const item = serverAppointment();
    const p = toUpdatePayload(item, form(), passthroughItems(item));
    expect((p.appointmentItems as unknown[]).length).toBe(2);
  });

  it('keeps the PACKAGE row and its fulfillments, which tie slots to this appointment', () => {
    const item = serverAppointment();
    const p = toUpdatePayload(item, form(), passthroughItems(item));
    const pkg = (p.appointmentItems as Record<string, unknown>[]).find((r) => r.type === 'PACKAGE');
    expect((pkg as Record<string, unknown>).fulfillments).toEqual([
      { fulfillmentId: 'uuid-f1', status: 'PENDING', linkedTransactionId: 12 },
    ]);
  });

  it('keeps each service line intact, UUID and snapshot included', () => {
    const item = serverAppointment();
    const p = toUpdatePayload(item, form(), passthroughItems(item));
    const line = (p.appointmentItems as Record<string, unknown>[])[0];
    expect(line.id).toBe('uuid-item-1');
    expect(line.serviceSnapshot).toEqual({ name: 'Gold Facial Treatment' });
    expect(line.servicePersonId).toBe(2);
  });

  it('strips the derived keys, including the one that is NOT read-only server-side', () => {
    const p = toUpdatePayload(serverAppointment(), form(), []);
    for (const key of DERIVED_KEYS) expect(p).not.toHaveProperty(key);
  });

  it('sends notes as a string always, so a cleared note actually clears', () => {
    expect(toUpdatePayload(serverAppointment(), form({ notes: '' }), []).notes).toBe('');
  });
});

describe('buildCreatePayload', () => {
  const form: AppointmentFormState = {
    ...toFormState(null),
    customerId: 7,
    date: '2026-08-05',
    time: '10:00',
    lines: [newServiceLine(21, 2500, null)],
  };

  it('carries the required fields and no id', () => {
    const p = buildCreatePayload(form, 3);
    expect(p.businessId).toBe(3);
    expect(p.appointmentStatus).toBe('CONFIRMED');
    expect(p.appointmentDateTime).toBe('2026-08-05T10:00:00');
    expect(p.totalAmount).toBe(2500);
    expect(p).not.toHaveProperty('id');
  });

  it('sends no partial package back-link, which the server rejects with a 400', () => {
    const p = buildCreatePayload(form, 3);
    expect(p).not.toHaveProperty('orderId');
    expect(p).not.toHaveProperty('fulfillmentIds');
  });
});

describe('read-mode helpers', () => {
  it('reads the enriched mirror, so view mode needs no catalog', () => {
    expect(enrichedDisplay(serverAppointment())[21]).toEqual({
      name: 'Gold Facial Treatment',
      duration: 75,
      unitPrice: 2500,
    });
    expect(enrichedDisplay(null)).toEqual({});
  });

  it('pluralises the count and adds the package rows in', () => {
    expect(serviceCountLabel([{} as ServiceLine])).toBe('1 service');
    expect(serviceCountLabel([{} as ServiceLine], [{}])).toBe('2 services');
  });

  it('totals the services plus the package rows', () => {
    const lines = [newServiceLine(21, 2500, null)];
    expect(appointmentTotal(lines, [{ totalPrice: 2500 }])).toBe(5000);
  });

  it('reports the bill and the lock', () => {
    expect(billLine(serverAppointment())).toBe('Not on a bill yet');
    expect(billLine({ billNumber: 'BILL-1' })).toBe('On bill BILL-1');
    expect(isBilled({ isBilled: true })).toBe(true);
  });

  it('labels statuses', () => {
    expect(statusLabel('IN_PROGRESS')).toBe('In Progress');
    expect(statusLabel('SOMETHING')).toBe('SOMETHING');
    expect(statusLabel(null)).toBe('');
  });
});
